import js from "@eslint/js";

export default [
    js.configs.recommended,
    {
        ignores: ["node_modules/**", "dist/**"],
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            globals: {
                window: "readonly",
                console: "readonly",
                Phaser: "readonly",
                __dirname: "readonly",
                document: "readonly",
                navigator: "readonly",
                Image: "readonly",
                Audio: "readonly",
                HTMLCanvasElement: "readonly",
                HTMLVideoElement: "readonly",
                HTMLElement: "readonly",
                Element: "readonly",
                DOMParser: "readonly",
                XMLSerializer: "readonly",
                FontFace: "readonly",
                AudioContext: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                performance: "readonly",
                screen: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                URL: "readonly",
                Blob: "readonly",
                FileReader: "readonly",
                XMLHttpRequest: "readonly",
                atob: "readonly",
                btoa: "readonly",
                process: "readonly",
                ActiveXObject: "readonly",
                MutationObserver: "readonly",
                fetch: "readonly",
            },
        },
        rules: {
            indent: ["error", 4],
            "linebreak-style": ["error", "unix"],
            quotes: ["error", "single"],
            semi: ["error", "always"],
            "no-unused-vars": "warn",
            "no-console": "off",
        },
    },
];
